import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/models.ts",
    "src/mcp/index.ts",
    "src/vectorstores/index.ts",
    "src/types.ts",
    "src/tools/index.ts",
    "src/utils.ts",
    "src/local-models/index.ts",
    "src/vectorstores/fulltext/index.ts",
    "src/const.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
  treeshake: true,
  minify: false,
  outDir: "dist",
  external: [
    "@langchain/community",
    "@langchain/core",
    "@langchain/openai",
    "@langchain/pinecone",
    "@langchain/qdrant",
    "@langchain/weaviate",
    "@pinecone-database/pinecone",
    "@qdrant/js-client-rest",
    "weaviate-client",
    "@zilliz/milvus2-sdk-node",
    "@supabase/supabase-js",
    "@lancedb/lancedb",
    "faiss-node",
    "chromadb",
    "@chroma-core/default-embed",
    "onnxruntime-node",
    "@huggingface/transformers",
    "better-sqlite3",
    "sqlite3",
    "pg",
    "@orama/orama",
    "flexsearch",
    "minisearch",
  ],
  onSuccess: "tsc --noEmit || true",
});
