import type { ProviderConfig } from "./types";
import type {
  FullTextSearchTool,
  VectorStoreProvider,
} from "./vectorstores/types";

export const PROVIDER_CONFIGS: ProviderConfig[] = [
  {
    id: "vercel",
    name: "Vercel Gateway",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    matchPatterns: ["vercel"],
    recommended: true,
    apiKeyDocs: "https://vercel.com/docs/ai-gateway/authentication", // API key auth docs
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "sk-...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://ai-gateway.vercel.sh/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "openai-compatible",
    name: "OpenAI Compatible API",
    matchPatterns: ["custom", "openai-compatible"],
    recommended: true,
    capabilities: ["embedding", "language", "image"],
    apiKeyDocs:
      "https://docs.vllm.ai/en/stable/serving/openai_compatible_server/",
    fields: [
      {
        id: "baseUrl",
        name: "Base URL",
        isRequired: true,
        type: "url",
        placeholder: "https://api.example.com/v1",
      },
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "sk-...",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },

  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    apiKeyDocs: "https://platform.openai.com/api-keys",
    matchPatterns: ["openai"],
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "sk-...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.openai.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    matchPatterns: ["anthropic", "claude"],
    apiKeyDocs: "https://platform.claude.com/settings/keys",
    capabilities: ["language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "sk-ant-...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.anthropic.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "google",
    name: "Google AI",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    matchPatterns: ["google", "gemini"],
    apiKeyDocs: "https://ai.google.dev/gemini-api/docs/api-key",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "AIza...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://generativelanguage.googleapis.com/v1beta",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    matchPatterns: ["groq"],
    apiKeyDocs: "https://console.groq.com/docs/quickstart",
    capabilities: ["language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "gsk_...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.groq.com/openai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    matchPatterns: ["deepseek"],
    apiKeyDocs: "https://platform.deepseek.com/api_keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "sk-...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.deepseek.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "together",
    name: "Together AI",
    baseUrl: "https://api.together.xyz/v1",
    matchPatterns: ["together"],
    apiKeyDocs: "https://docs.together.ai/docs/authentication",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.together.xyz/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    baseUrl: "https://api.mistral.ai/v1",
    matchPatterns: ["mistral"],
    apiKeyDocs: "https://docs.mistral.ai/getting-started/quickstart/",
    capabilities: ["embedding", "language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.mistral.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    baseUrl: "https://api.cohere.ai/v2",
    matchPatterns: ["cohere"],
    apiKeyDocs: "https://dashboard.cohere.com/api-keys",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.cohere.ai/v2",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "perplexity",
    name: "Perplexity",
    baseUrl: "https://api.perplexity.ai",
    matchPatterns: ["perplexity"],
    apiKeyDocs: "https://docs.perplexity.ai",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "pplx-...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.perplexity.ai",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "fireworks",
    name: "Fireworks AI",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    matchPatterns: ["fireworks"],
    apiKeyDocs: "https://fireworks.ai/api-keys",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "fw_...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.fireworks.ai/inference/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "replicate",
    name: "Replicate",
    baseUrl: "https://api.replicate.com/v1",
    matchPatterns: ["replicate"],
    apiKeyDocs: "https://replicate.com/account/api-tokens",
    capabilities: ["language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "r8_...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.replicate.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    baseUrl: "https://router.huggingface.co/v1",
    matchPatterns: ["huggingface", "hugging face"],
    apiKeyDocs: "https://huggingface.co/settings/tokens",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "hf_...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://router.huggingface.co/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    baseUrl: "https://api.deepinfra.com/v1",
    matchPatterns: ["deepinfra"],
    apiKeyDocs: "https://deepinfra.com/dash/api_keys",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.deepinfra.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "cerebras",
    name: "Cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    matchPatterns: ["cerebras"],
    apiKeyDocs: "https://cloud.cerebras.ai",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.cerebras.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "xai",
    name: "xAI",
    baseUrl: "https://api.x.ai/v1",
    matchPatterns: ["xai", "x.ai"],
    apiKeyDocs: "https://console.x.ai/",
    capabilities: ["language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "xai-...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.x.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },

  // Providers with dynamic base URLs
  {
    id: "azure",
    name: "Azure OpenAI",
    matchPatterns: ["azure"],
    apiKeyDocs:
      "https://learn.microsoft.com/azure/ai-services/openai/how-to/create-resource",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "baseUrl",
        name: "Endpoint",
        isRequired: true,
        type: "url",
        placeholder: "https://YOUR-RESOURCE.openai.azure.com",
      },
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "deployment",
        name: "Deployment Name",
        isRequired: false,
        type: "text",
        placeholder: "gpt-4",
      },
      {
        id: "apiVersion",
        name: "API Version",
        isRequired: false,
        type: "text",
        placeholder: "2023-03-15-preview",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },

  // {
  //   id: "ollama",
  //   name: "Ollama",
  //   matchPatterns: ["ollama"],
  //   apiKeyDocs: "",
  //   capabilities: ["embedding", "language", "image"],
  //   fields: [
  //     {
  //       id: "baseUrl",
  //       name: "Base URL",
  //       isRequired: true,
  //       type: "url",
  //       placeholder: "http://localhost:11434",
  //     },
  //     // {
  //     //   id: "proxy",
  //     //   name: "HTTP Proxy",
  //     //   isRequired: false,
  //     //   type: "url",
  //     //   placeholder: "http://proxy.example.com:8080",
  //     // },
  //   ],
  // },

  // Special providers
  {
    id: "alibaba",
    name: "Alibaba Cloud",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    matchPatterns: ["alibaba", "dashscope"],
    apiKeyDocs:
      "https://help.aliyun.com/zh/dashscope/developer-reference/get-api-key",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "sk-...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "voyage",
    name: "Voyage AI",
    baseUrl: "https://api.voyageai.com/v1",
    matchPatterns: ["voyage"],
    apiKeyDocs: "https://dash.voyageai.com/api-keys",
    capabilities: ["embedding"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "pa-...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.voyageai.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },

  {
    id: "amazon",
    name: "Amazon Bedrock",
    matchPatterns: ["amazon", "bedrock"],
    apiKeyDocs:
      "https://docs.aws.amazon.com/bedrock/latest/userguide/setting-up.html",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "region",
        name: "Region",
        isRequired: true,
        type: "text",
        placeholder: "us-east-1",
      },
      {
        id: "accessKey",
        name: "Access Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "secretKey",
        name: "Secret Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "arcee-ai",
    name: "Arcee AI",
    baseUrl: "https://api.arcee.ai/v1",
    matchPatterns: ["arcee", "arcee-ai"],
    apiKeyDocs: "https://app.arcee.ai/api-keys",
    capabilities: ["embedding", "language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.arcee.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "bfl",
    name: "BFL AI",
    baseUrl: "https://api.bfl.ai/v1",
    matchPatterns: ["bfl"],
    apiKeyDocs: "https://api.bfl.ai/dashboard",
    capabilities: ["image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.bfl.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  // {
  //   id: "inception",
  //   name: "Inception AI",
  //   baseUrl: "https://api.inception.ai/v1",
  //   matchPatterns: ["inception"],
  //   capabilities: ["language"],
  //   fields: [
  //     {
  //       id: "apiKey",
  //       name: "API Key",
  //       isRequired: true,
  //       type: "password",
  //     },
  //     {
  //       id: "baseUrl",
  //       name: "Base URL Override",
  //       isRequired: false,
  //       type: "url",
  //       placeholder: "https://api.inception.ai/v1",
  //     },
  //     {
  //       id: "proxy",
  //       name: "HTTP Proxy",
  //       isRequired: false,
  //       type: "url",
  //       placeholder: "http://proxy.example.com:8080",
  //     },
  //   ],
  // },
  {
    id: "kwaipilot",
    name: "Kwai Pilot",
    baseUrl: "https://api.kwaipilot.com/v1",
    matchPatterns: ["kwaipilot", "kwai"],
    apiKeyDocs: "https://console.kwaipilot.com/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.kwaipilot.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "meituan",
    name: "Meituan AI",
    baseUrl: "https://api.meituan.com/ai/v1",
    matchPatterns: ["meituan"],
    apiKeyDocs: "https://ai.meituan.com/docs",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.meituan.com/ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "meta",
    name: "Meta AI",
    baseUrl: "https://api.meta.ai/v1",
    matchPatterns: ["meta", "llama"],
    apiKeyDocs: "https://developers.facebook.com/docs/ai/",
    capabilities: ["language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.meta.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "minimax",
    name: "MiniMax",
    baseUrl: "https://api.minimax.chat/v1",
    matchPatterns: ["minimax"],
    apiKeyDocs: "https://www.minimaxi.com/document/ChatCompletion-en",
    capabilities: ["language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.minimax.chat/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "moonshotai",
    name: "Moonshot AI",
    baseUrl: "https://api.moonshot.cn/v1",
    matchPatterns: ["moonshot", "moonshotai", "kimi"],
    apiKeyDocs: "https://platform.moonshot.cn/console/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.moonshot.cn/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "morph",
    name: "Morph AI",
    baseUrl: "https://api.morph.ai/v1",
    matchPatterns: ["morph"],
    apiKeyDocs: "https://dashboard.morph.ai/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.morph.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    matchPatterns: ["nvidia", "nim"],
    apiKeyDocs: "https://build.nvidia.com/explore/discover",
    capabilities: ["embedding", "language", "image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://integrate.api.nvidia.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "prime-intellect",
    name: "Prime Intellect",
    baseUrl: "https://api.primeintellect.ai/v1",
    matchPatterns: ["prime-intellect"],
    apiKeyDocs: "https://console.primeintellect.ai/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.primeintellect.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  // {
  //   id: "stealth",
  //   name: "Stealth AI",
  //   baseUrl: "https://api.stealth.ai/v1",
  //   matchPatterns: ["stealth"],
  //   apiKeyDocs: "https://console.stealth.ai/api-keys",
  //   capabilities: ["language"],
  //   fields: [
  //     {
  //       id: "apiKey",
  //       name: "API Key",
  //       isRequired: true,
  //       type: "password",
  //     },
  //     {
  //       id: "baseUrl",
  //       name: "Base URL Override",
  //       isRequired: false,
  //       type: "url",
  //       placeholder: "https://api.stealth.ai/v1",
  //     },
  //     {
  //       id: "proxy",
  //       name: "HTTP Proxy",
  //       isRequired: false,
  //       type: "url",
  //       placeholder: "http://proxy.example.com:8080",
  //     },
  //   ],
  // },
  {
    id: "zai",
    name: "ZAI",
    baseUrl: "https://api.zai.ai/v1",
    matchPatterns: ["zai"],
    apiKeyDocs: "https://console.zai.ai/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.zai.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },

  // provided by ai-sdk not ai-gateway
  {
    id: "fal",
    name: "Fal AI",
    baseUrl: "https://api.fal.ai/v1",
    matchPatterns: ["fal"],
    apiKeyDocs: "https://fal.ai/dashboard/keys",
    capabilities: ["image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.fal.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "black-forest-labs",
    name: "Black Forest Labs",
    baseUrl: "https://api.bfl.ai/v1",
    matchPatterns: ["black-forest-labs", "bfl", "flux"],
    apiKeyDocs: "https://api.bfl.ai/dashboard",
    capabilities: ["image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.bfl.ai/v1",
      },
      {
        id: "region",
        name: "Region",
        isRequired: false,
        type: "text",
        placeholder: "us (options: us, eu)",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "luma",
    name: "Luma AI",
    baseUrl: "https://api.lumalabs.ai/v1",
    matchPatterns: ["luma", "dream-machine"],
    apiKeyDocs: "https://lumalabs.ai/account/api-keys",
    capabilities: ["image"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.lumalabs.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    baseUrl: "https://api.elevenlabs.io/v1",
    matchPatterns: ["elevenlabs", "11labs"],
    apiKeyDocs: "https://elevenlabs.io/app/settings/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.elevenlabs.io/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "lmnt",
    name: "LMNT",
    baseUrl: "https://api.lmnt.com/v1",
    matchPatterns: ["lmnt"],
    apiKeyDocs: "https://dashboard.lmnt.com/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.lmnt.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "hume",
    name: "Hume AI",
    baseUrl: "https://api.hume.ai/v1",
    matchPatterns: ["hume"],
    apiKeyDocs: "https://platform.hume.ai/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.hume.ai/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "deepgram",
    name: "Deepgram",
    baseUrl: "https://api.deepgram.com/v1",
    matchPatterns: ["deepgram"],
    apiKeyDocs: "https://console.deepgram.com/project",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.deepgram.com/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "assemblyai",
    name: "AssemblyAI",
    baseUrl: "https://api.assemblyai.com/v2",
    matchPatterns: ["assemblyai", "assembly"],
    apiKeyDocs: "https://www.assemblyai.com/app/account",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.assemblyai.com/v2",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  {
    id: "gladia",
    name: "Gladia",
    baseUrl: "https://api.gladia.io/v1",
    matchPatterns: ["gladia"],
    apiKeyDocs: "https://portal.gladia.io/api-keys",
    capabilities: ["language"],
    fields: [
      {
        id: "apiKey",
        name: "API Key",
        isRequired: true,
        type: "password",
        placeholder: "...",
      },
      {
        id: "baseUrl",
        name: "Base URL Override",
        isRequired: false,
        type: "url",
        placeholder: "https://api.gladia.io/v1",
      },
      {
        id: "proxy",
        name: "HTTP Proxy",
        isRequired: false,
        type: "url",
        placeholder: "http://proxy.example.com:8080",
      },
    ],
  },
  // {
  //   id: "rev-ai",
  //   name: "Rev.ai",
  //   baseUrl: "https://api.rev.ai/speechtotext/v1",
  //   matchPatterns: ["rev", "rev-ai", "rev.ai"],
  //   apiKeyDocs: "https://www.rev.ai/access_token",
  //   capabilities: ["language"],
  //   fields: [
  //     {
  //       id: "apiKey",
  //       name: "Access Token",
  //       isRequired: true,
  //       type: "password",
  //       placeholder: "...",
  //     },
  //     {
  //       id: "baseUrl",
  //       name: "Base URL Override",
  //       isRequired: false,
  //       type: "url",
  //       placeholder: "https://api.rev.ai/speechtotext/v1",
  //     },
  //     {
  //       id: "proxy",
  //       name: "HTTP Proxy",
  //       isRequired: false,
  //       type: "url",
  //       placeholder: "http://proxy.example.com:8080",
  //     },
  //   ],
  // },
  // {
  //   id: "baseten",
  //   name: "Baseten",
  //   baseUrl: "https://api.baseten.co/v1",
  //   matchPatterns: ["baseten"],
  //   apiKeyDocs: "https://dashboard.baseten.co/settings/service-accounts",
  //   capabilities: ["language", "image"],
  //   fields: [
  //     {
  //       id: "apiKey",
  //       name: "API Key",
  //       isRequired: true,
  //       type: "password",
  //       placeholder: "...",
  //     },
  //     {
  //       id: "baseUrl",
  //       name: "Base URL Override",
  //       isRequired: false,
  //       type: "url",
  //       placeholder: "https://api.baseten.co/v1",
  //     },
  //     {
  //       id: "proxy",
  //       name: "HTTP Proxy",
  //       isRequired: false,
  //       type: "url",
  //       placeholder: "http://proxy.example.com:8080",
  //     },
  //   ],
  // },
];

// Vectorstores
export const ALL_VECTOR_STORES: VectorStoreProvider[] = [
  {
    id: "faiss",
    name: "Faiss",
    description: "Local vector store, fast and efficient",
    credentials: [],
    isLocalOnly: true,
    supportsFullTextSearch: false,
    fullTextSearchConfig: {
      searchType: "external", // Needs external tool
    },
    needsCredentials: false,
  },
  {
    id: "pinecone",
    name: "Pinecone",
    supportsFullTextSearch: true,
    description: "Pinecone vector store, cloud-based and scalable",
    fullTextSearchConfig: {
      searchType: "native",
      nativeAlgorithm: "bm25",
      requiresSetup: false,
    },
    credentials: [
      {
        id: "apiKey",
        name: "Pinecone API Key",
        isRequired: true,
        isSecret: true,
      },
      {
        id: "collectionName",
        name: "Pinecone Index",
        isRequired: true,
      },
    ],
    needsCredentials: true,
  },
  {
    id: "qdrant",
    name: "Qdrant",
    description: "Qdrant vector store, cloud-based and scalable",
    supportsFullTextSearch: true,
    fullTextSearchConfig: {
      searchType: "native",
      nativeAlgorithm: "bm25",
      requiresSetup: false,
    },
    credentials: [
      {
        id: "url",
        name: "Qdrant URL",
        isRequired: true,
      },
      {
        id: "apiKey",
        name: "Qdrant API Key",
        isRequired: false,
        isSecret: true,
        cloudOnly: true,
      },
      {
        id: "collection",
        name: "Collection Name",
        isRequired: false,
        cloudOnly: false,
      },
    ],
    needsCredentials: true,
  },
  {
    id: "lancedb",
    name: "LanceDB",
    supportsFullTextSearch: true,
    description: "LanceDB, columnar, local-first vector database",
    fullTextSearchConfig: {
      searchType: "native",
      nativeAlgorithm: "bm25",
      requiresSetup: true,
      setupInstructions:
        "Full-text search requires creating a text index on your table",
      setupDocUrl: "https://docs.lancedb.com/search/full-text-search",
      configFields: [
        {
          id: "ftsField",
          name: "Full-Text Search Field",
          description: "Field name to index for full-text search",
          isRequired: true,
          placeholder: "text",
        },
      ],
    },
    credentials: [
      {
        id: "uri",
        name: "URI",
        isRequired: false,
        cloudOnly: true,
      },
      {
        id: "apiKey",
        isSecret: true,
        name: "API Key",
        isRequired: false,
        cloudOnly: true,
      },
      {
        id: "region",
        name: "Region",
        isRequired: false,
        cloudOnly: true,
      },
      {
        id: "collection",
        name: "Table Name",
        isRequired: false,
      },
    ],
    needsCredentials: false,
  },
  {
    id: "chroma",
    name: "Chroma",
    supportsFullTextSearch: true,
    isLocalOnly: false,
    apiKeyDocs: "https://docs.trychroma.com/",
    description: "Open-source embedding database (local or cloud)",
    fullTextSearchConfig: {
      searchType: "external", // Chroma doesn't have native full-text
    },
    credentials: [
      {
        id: "host",
        name: "Host",
        isRequired: true,
        default: "localhost",
        placeholder: "localhost or api.trychroma.com",
        description: "Chroma server host (default: localhost for local)",
      },
      {
        id: "port",
        name: "Port",
        isRequired: false,
        default: "8000",
        placeholder: "8000",
        description: "Chroma server port",
      },
      {
        id: "ssl",
        name: "Use SSL",
        isRequired: false,
        default: false,
        description: "Enable SSL connection",
      },
      {
        id: "apiKey",
        name: "API Key",
        isRequired: false,
        isSecret: true,
        cloudOnly: true,
      },
      {
        id: "tenant",
        name: "Tenant",
        isRequired: true,
        cloudOnly: true,
        placeholder: "default-tenant",
        description: "Required for Chroma Cloud",
      },
      {
        id: "database",
        name: "Database",
        isRequired: true,
        cloudOnly: true,
        placeholder: "default_database",
        description: "Required for Chroma Cloud",
      },
      {
        id: "collection",
        name: "Collection Name",
        isRequired: true,
        placeholder: "my-collection",
        description: "Name of the collection to use/create",
      },
    ],
    needsCredentials: true,
  },
  {
    id: "milvus",
    name: "Milvus",
    isLocalOnly: false,
    supportsFullTextSearch: true,
    apiKeyDocs: "https://cloud.zilliz.com/",
    description:
      "Scalable and high-performance vector database (local or cloud)",
    fullTextSearchConfig: {
      searchType: "native",
      nativeAlgorithm: "bm25",
      requiresSetup: true,
      setupInstructions: "Enable full-text search when creating the collection",
      setupDocUrl: "https://milvus.io/docs/full-text-search.md",
      configFields: [
        {
          id: "enableFullTextSearch",
          name: "Enable Full-Text Search",
          description: "Must be enabled during collection creation",
          isRequired: false,
          default: true,
        },
      ],
    },
    credentials: [
      {
        id: "address",
        name: "Address/URL",
        isRequired: true,
        placeholder: "localhost:19530 or https://your-cluster.cloud.milvus.io",
        description: "Milvus server address (host:port or full URL)",
      },
      {
        id: "collection",
        name: "Collection Name",
        isRequired: true,
        placeholder: "my_collection",
        description: "Name of the collection to use/create",
      },
      {
        id: "token",
        name: "Token",
        isRequired: false,
        isSecret: true,
        placeholder: "API token for cloud or combined username:password",
        description: "Cloud API token or 'username:password' format",
      },
      {
        id: "username",
        name: "Username",
        isRequired: false,
        default: "root",
        placeholder: "root",
        description: "Username for authentication (local default: root)",
      },
      {
        id: "password",
        name: "Password",
        isRequired: false,
        isSecret: true,
        placeholder: "Milvus",
        description: "Password for authentication (local default: Milvus)",
      },
      {
        id: "database",
        name: "Database",
        isRequired: false,
        default: "default",
        placeholder: "default",
        description: "Database name (optional)",
      },
      {
        id: "ssl",
        name: "Use SSL",
        isRequired: false,
        default: false,
        description: "Enable SSL connection (auto-detected for HTTPS URLs)",
      },
    ],
    needsCredentials: true,
  },
  {
    id: "pgvector",
    name: "pgvector",
    description: "PostgreSQL with pgvector extension",
    supportsFullTextSearch: true,
    fullTextSearchConfig: {
      searchType: "native",
      nativeAlgorithm: "tfidf", // PostgreSQL uses tsvector
      requiresSetup: true,
      setupInstructions:
        "Requires creating GIN or GiST index on tsvector column",
      setupDocUrl: "https://www.postgresql.org/docs/current/textsearch.html",
      configFields: [
        {
          id: "ftsColumn",
          name: "Full-Text Search Column",
          description: "Name of the tsvector column for full-text search",
          isRequired: false,
          default: "content_tsv",
          placeholder: "content_tsv",
        },
      ],
    },
    credentials: [
      {
        id: "host",
        name: "Host",
        isRequired: true,
      },
      {
        id: "port",
        name: "Port",
        isRequired: false,
      },
      {
        id: "database",
        name: "Database",
        isRequired: true,
      },
      {
        id: "user",
        name: "User",
        isRequired: true,
      },
      {
        id: "password",
        name: "Password",
        isRequired: true,
      },
      {
        id: "ssl",
        name: "SSL Enabled",
        isRequired: false,
      },
      {
        id: "tableName",
        name: "Table Name",
        isRequired: true,
      },
    ],
    needsCredentials: true,
  },
  {
    id: "supabase",
    name: "Supabase",
    supportsFullTextSearch: true,
    description: "Supabase vector database with pgvector extension",
    apiKeyDocs: "https://supabase.com/dashboard/project/_/settings/api",
    fullTextSearchConfig: {
      searchType: "native",
      nativeAlgorithm: "tfidf",
      requiresSetup: true,
      setupInstructions:
        "Create a tsvector column and GIN index for full-text search",
      setupDocUrl: "https://supabase.com/docs/guides/database/full-text-search",
      configFields: [
        {
          id: "ftsColumn",
          name: "Full-Text Search Column",
          description: "Name of the tsvector column",
          isRequired: false,
          default: "fts",
          placeholder: "fts",
        },
      ],
    },
    credentials: [
      {
        id: "tableName",
        name: "Table Name",
        isRequired: false,
      },
      {
        id: "url",
        name: "Supabase Project URL",
        isRequired: true,
      },
      {
        id: "apiKey",
        isSecret: true,
        name: "Supabase Private/Service Role Key",
        isRequired: true,
      },
    ],
    needsCredentials: true,
  },
  {
    id: "weaviate",
    name: "Weaviate",
    description: "Weaviate vector database, cloud-native and modular",
    apiKeyDocs: "https://console.weaviate.cloud/",
    supportsFullTextSearch: true,
    fullTextSearchConfig: {
      searchType: "native",
      nativeAlgorithm: "bm25",
      requiresSetup: false,
    },
    credentials: [
      {
        id: "collection",
        name: "Class/Collection Name",
        isRequired: true,
      },
      {
        id: "url",
        name: "Weaviate URL",
        isRequired: true,
      },
      {
        id: "apiKey",
        isSecret: true,
        name: "Weaviate API Key",
        isRequired: false,
        cloudOnly: true,
      },
    ],
    needsCredentials: true,
  },
];

export const FULLTEXT_SEARCH_TOOLS: FullTextSearchTool[] = [
  {
    id: "flexsearch",
    name: "FlexSearch",
    description: "Fast and memory-efficient full-text search",
    bestFor: "Large datasets (10K+ documents)",
    maxDocuments: 100000,
  },
  {
    id: "minisearch",
    name: "MiniSearch",
    description: "Lightweight full-text search with fuzzy matching",
    bestFor: "Small to medium datasets (up to 10K documents)",
    maxDocuments: 10000,
  },
  {
    id: "orama",
    name: "Orama",
    description: "Modern full-text search with typo tolerance",
    bestFor: "Medium datasets with advanced search features",
    maxDocuments: 50000,
  },
];

// export const ALL_VECTOR_STORES: VectorStoreProvider[] = [
//   {
//     id: "faiss",
//     name: "Faiss",
//     description: "Local vector store, fast and efficient",
//     credentials: [],
//     isLocalOnly: true,
//     supportsFullTextSearch: false,
//     needsCredentials: false,
//   },
//   {
//     id: "pinecone",
//     name: "Pinecone",
//     supportsFullTextSearch: true,
//     description: "Pinecone vector store, cloud-based and scalable",
//     credentials: [
//       {
//         id: "apiKey",
//         name: "Pinecone API Key",
//         isRequired: true,
//         isSecret: true,
//       },
//       {
//         id: "collectionName",
//         name: "Pinecone Index",
//         isRequired: true,
//       },
//     ],
//     needsCredentials: true,
//   },
//   {
//     id: "qdrant",
//     name: "Qdrant",
//     description: "Qdrant vector store, cloud-based and scalable",
//     supportsFullTextSearch: true,
//     credentials: [
//       {
//         id: "url",
//         name: "Qdrant URL",
//         isRequired: true,
//       },
//       {
//         id: "apiKey",
//         name: "Qdrant API Key",
//         isRequired: false,
//         isSecret: true,
//         cloudOnly: true,
//       },
//       {
//         id: "collection",
//         name: "Collection Name",
//         isRequired: false,
//         cloudOnly: false,
//       },
//     ],
//     needsCredentials: true,
//   },
//   {
//     id: "lancedb",
//     name: "LanceDB",
//     supportsFullTextSearch: true,
//     description: "LanceDB, columnar, local-first vector database",
//     credentials: [
//       {
//         id: "uri",
//         name: "URI",
//         isRequired: false,
//         cloudOnly: true,
//       },
//       {
//         id: "apiKey",
//         isSecret: true,
//         name: "API Key",
//         isRequired: false, // for managed LanceDB cloud
//         cloudOnly: true,
//       },
//       {
//         id: "region",
//         name: "Region",
//         isRequired: false,
//         cloudOnly: true,
//       },
//       {
//         id: "collection",
//         name: "Table Name",
//         isRequired: false,
//       },
//     ],
//     needsCredentials: false,
//   },
//   {
//     id: "chroma",
//     name: "Chroma",
//     supportsFullTextSearch: true,
//     isLocalOnly: false,
//     apiKeyDocs: "https://docs.trychroma.com/",
//     description: "Open-source embedding database (local or cloud)",
//     credentials: [
//       {
//         id: "host",
//         name: "Host",
//         isRequired: false,
//         default: "localhost",
//         placeholder: "localhost or api.trychroma.com",
//         description: "Chroma server host (default: localhost for local)",
//       },
//       {
//         id: "port",
//         name: "Port",
//         isRequired: false,
//         default: "8000",
//         placeholder: "8000",
//         description: "Chroma server port",
//       },
//       {
//         id: "ssl",
//         name: "Use SSL",
//         isRequired: false,
//         default: false,
//         description: "Enable SSL connection",
//       },
//       {
//         id: "apiKey",
//         name: "API Key",
//         isRequired: false,
//         isSecret: true,
//         cloudOnly: true,
//       },
//       {
//         id: "tenant",
//         name: "Tenant",
//         isRequired: false,
//         cloudOnly: true,
//         placeholder: "default-tenant",
//         description: "Required for Chroma Cloud",
//       },
//       {
//         id: "database",
//         name: "Database",
//         isRequired: false,
//         cloudOnly: true,
//         placeholder: "default_database",
//         description: "Required for Chroma Cloud",
//       },
//       {
//         id: "collection",
//         name: "Collection Name",
//         isRequired: true,
//         placeholder: "my-collection",
//         description: "Name of the collection to use/create",
//       },
//     ],
//     needsCredentials: false, // Local mode doesn't need credentials
//   },

//   {
//     id: "milvus",
//     name: "Milvus",
//     isLocalOnly: false,
//     supportsFullTextSearch: true,
//     apiKeyDocs: "https://cloud.zilliz.com/",
//     description:
//       "Scalable and high-performance vector database (local or cloud)",
//     credentials: [
//       {
//         id: "address",
//         name: "Address/URL",
//         isRequired: true,
//         placeholder: "localhost:19530 or https://your-cluster.cloud.milvus.io",
//         description: "Milvus server address (host:port or full URL)",
//       },
//       {
//         id: "collection",
//         name: "Collection Name",
//         isRequired: true,
//         placeholder: "my_collection",
//         description: "Name of the collection to use/create",
//       },
//       {
//         id: "token",
//         name: "Token",
//         isRequired: false,
//         isSecret: true,
//         placeholder: "API token for cloud or combined username:password",
//         description: "Cloud API token or 'username:password' format",
//       },
//       {
//         id: "username",
//         name: "Username",
//         isRequired: false,
//         default: "root",
//         placeholder: "root",
//         description: "Username for authentication (local default: root)",
//       },
//       {
//         id: "password",
//         name: "Password",
//         isRequired: false,
//         isSecret: true,
//         placeholder: "Milvus",
//         description: "Password for authentication (local default: Milvus)",
//       },
//       {
//         id: "database",
//         name: "Database",
//         isRequired: false,
//         default: "default",
//         placeholder: "default",
//         description: "Database name (optional)",
//       },

//       {
//         id: "ssl",
//         name: "Use SSL",
//         isRequired: false,
//         default: false,
//         description: "Enable SSL connection (auto-detected for HTTPS URLs)",
//       },
//       {
//         id: "enableFullTextSearch",
//         name: "Enable Full-Text Search",
//         isRequired: false,
//         default: true,
//         description: "Enable BM25 full-text search capabilities",
//       },
//     ],
//     needsCredentials: true,
//   },
//   {
//     id: "pgvector",
//     name: "pgvector",
//     description: "PostgreSQL with pgvector extension",
//     credentials: [
//       {
//         id: "host",
//         name: "Host",
//         isRequired: true,
//       },
//       {
//         id: "port",
//         name: "Port",
//         isRequired: false, // defaults to 5432
//       },
//       {
//         id: "database",
//         name: "Database",
//         isRequired: true,
//       },
//       {
//         id: "user",
//         name: "User",
//         isRequired: true,
//       },
//       {
//         id: "password",
//         name: "Password",
//         isRequired: true,
//       },
//       {
//         id: "ssl",
//         name: "SSL Enabled",
//         isRequired: false, // boolean or SSL config
//       },
//       {
//         id: "tableName",
//         name: "Table Name",
//         isRequired: true,
//       },
//     ],
//     needsCredentials: true,
//   },
//   {
//     id: "supabase",
//     name: "Supabase",
//     supportsFullTextSearch: true,
//     description: "Supabase vector database with pgvector extension",
//     apiKeyDocs: "https://supabase.com/dashboard/project/_/settings/api",
//     credentials: [
//       {
//         id: "tableName",
//         name: "Table Name",
//         isRequired: false,
//       },
//       {
//         id: "url",
//         name: "Supabase Project URL",
//         isRequired: true,
//       },
//       {
//         id: "apiKey",
//         isSecret: true,
//         name: "Supabase Private/Service Role Key",
//         isRequired: true,
//       },
//     ],
//     needsCredentials: true,
//   },
//   {
//     id: "weaviate",
//     name: "Weaviate",
//     description: "Weaviate vector database, cloud-native and modular",
//     apiKeyDocs: "https://console.weaviate.cloud/",
//     credentials: [
//       {
//         id: "collection",
//         name: "Class/Collection Name",
//         isRequired: true,
//       },
//       {
//         id: "url",
//         name: "Weaviate URL",
//         isRequired: true,
//       },
//       {
//         id: "apiKey",
//         isSecret: true,
//         name: "Weaviate API Key",
//         isRequired: false,
//         cloudOnly: true,
//       },
//     ],
//     needsCredentials: true,
//   },
// ];
